import { ServiceOption } from './serviceTypes';

export const premiumServices: ServiceOption[] = [
  {
    id: 'premium-single',
    title: 'PREMIUM SINGLE UNIT',
    price: 80,
    description: 'EVAP COILS POWERJET WASH DEEP CLEAN INCLUDED',
    duration: '45 minutes',
    paddingBefore: 15,
    paddingAfter: 30,
  },
  {
    id: 'premium-2units',
    title: 'PREMIUM 2 UNITS',
    price: 120,
    usualPrice: 150,
    description: 'EVAP COILS POWERJET WASH DEEP CLEAN INCLUDED',
    duration: '1 hour',
    paddingBefore: 0,
    paddingAfter: 30,
  },
  {
    id: 'premium-3units',
    title: 'PREMIUM 3 UNITS',
    price: 180,
    usualPrice: 210,
    description: 'EVAP COILS POWERJET WASH DEEP CLEAN INCLUDED',
    duration: '1 hour',
    paddingBefore: 0,
    paddingAfter: 30,
  },
  {
    id: 'premium-4units',
    title: 'PREMIUM 4 UNITS',
    price: 240,
    usualPrice: 280,
    description: 'EVAP COILS POWERJET WASH DEEP CLEAN INCLUDED',
    duration: '1 hour',
    paddingBefore: 15,
    paddingAfter: 30,
  },
  {
    id: 'premium-5units',
    title: 'PREMIUM 5 UNITS',
    price: 300,
    usualPrice: 330,
    description: 'EVAP COILS POWERJET WASH DEEP CLEAN INCLUDED',
    duration: '1 hour 30 minutes',
    paddingBefore: 30,
    paddingAfter: 30,
  },
  {
    id: 'premium-6units',
    title: 'PREMIUM 6 UNITS',
    price: 360,
    usualPrice: 380,
    description: 'EVAP COILS POWERJET WASH DEEP CLEAN INCLUDED',
    duration: '1 hour 30 minutes',
    paddingBefore: 30,
    paddingAfter: 30,
  },
  {
    id: 'fault-checking',
    title: 'AC FAULT CHECKING/SITE INSPECTION',
    price: 120,
    description: 'ADVANCED TROUBLESHOOTING FOR BLINKING OR SEVERE BREAKDOWNS',
    duration: '1 hour',
    paddingBefore: 0,
    paddingAfter: 0,
  },
  {
    id: 'powerjet-chemical',
    title: 'POWERJET CHEMICAL WASH',
    price: 120,
    description: 'SIGNATURE POWERJET SERVICE WITH DEEP CLEANING USING COIL CHEMICALS',
    duration: '1 hour 30 minutes',
    paddingBefore: 0,
    paddingAfter: 0,
  },
  {
    id: 'gas-leakage',
    title: 'GAS CHECKING & LEAKAGE ISSUES',
    price: 125,
    description: 'FREQUENT GAS TOPUP & LEAKAGE ISSUES',
    duration: '1 hour',
    paddingBefore: 0,
    paddingAfter: 0,
  }
];