import { ServiceOption } from './serviceTypes';

export const serviceOptions: ServiceOption[] = [
  {
    id: 'single',
    title: '1 SINGLE UNIT',
    price: 60,
    description: 'COMPREHENSIVE NORMAL SERVICING OR ADDON $20 POWERJET ON EVAP COIL DEEP CLEAN (OPTIONAL)',
    duration: '45 minutes',
    paddingBefore: 15,
    paddingAfter: 30,
  },
  {
    id: '2units',
    title: '2 UNITS',
    price: 60,
    usualPrice: 90,
    description: 'COMPREHENSIVE NORMAL SERVICING OR ADDON $30 POWERJET ON EVAP COIL PER AC (OPTIONAL)',
    duration: '45 minutes',
    paddingBefore: 0,
    paddingAfter: 30,
  },
  {
    id: '3units',
    title: '3 UNITS',
    price: 90,
    usualPrice: 120,
    description: 'COMPREHENSIVE NORMAL SERVICING OR ADDON $30 POWERJET ON EVAP COIL PER AC (OPTIONAL)',
    duration: '1 hour',
    paddingBefore: 0,
    paddingAfter: 30,
  },
  {
    id: '4units',
    title: '4 UNITS',
    price: 120,
    usualPrice: 160,
    description: 'COMPREHENSIVE NORMAL SERVICING OR ADDON $30 POWERJET ON EVAP COIL PER AC (OPTIONAL)',
    duration: '1 hour',
    paddingBefore: 0,
    paddingAfter: 30,
  },
  {
    id: '5units',
    title: '5 UNITS',
    price: 150,
    usualPrice: 180,
    description: 'COMPREHENSIVE NORMAL SERVICING OR ADDON $30 POWERJET ON EVAP COIL PER AC (OPTIONAL)',
    duration: '1 hour 30 minutes',
    paddingBefore: 0,
    paddingAfter: 30,
  },
  {
    id: '6units',
    title: '6 UNITS',
    price: 180,
    usualPrice: 200,
    description: 'COMPREHENSIVE NORMAL SERVICING OR ADDON $30 POWERJET ON EVAP COIL PER AC (OPTIONAL)',
    duration: '1 hour 30 minutes',
    paddingBefore: 0,
    paddingAfter: 30,
  },
  {
    id: '7units',
    title: '7 UNITS',
    price: 210,
    usualPrice: 280,
    description: 'COMPREHENSIVE NORMAL SERVICING OR ADDON $30 POWERJET ON EVAP COIL PER AC (OPTIONAL)',
    duration: '1 hour 30 minutes',
    paddingBefore: 30,
    paddingAfter: 30,
  },
  {
    id: '8plus',
    title: 'MORE THAN 8 AC UNITS',
    usualPrice: 320,
    price: 240,
    description: 'COMPREHENSIVE NORMAL SERVICING OR ADDON $30 POWERJET ON EVAP COIL PER AC (OPTIONAL)',
    duration: '1 hour 30 minutes',
    paddingBefore: 30,
    paddingAfter: 30,
  }
];