import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST);

// Handle installation
self.addEventListener('install', (event) => {
  self.skipWaiting();
});

// Handle activation
self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});

// Handle fetch events
self.addEventListener('fetch', (event) => {
  // Return cached response if available, otherwise fetch from network
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});